### ISSUE TITLE
Design application settings/pattern (Scale)

### ISSUE THREAD

**Issue by vz3** [18F/cg-design#5]

**Comment by vz3** [comment]
Everything is mocked up at 6 col width. Will get Sketch up too.
[Sketch file](https://github.com/18F/cg-design/files/425344/uswds.cg.fork.zip)
(Sorry for the zip, GitHub doesn't support Sketch)

# Patterns

![app settings](https://cloud.githubusercontent.com/assets/582918/17780620/0ba150f8-653a-11e6-82f1-0cfae1868c35.png)

# Normal (Default) state

![app settings normal state](https://cloud.githubusercontent.com/assets/582918/17780652/2ee1d6be-653a-11e6-87a5-ce46b301d9c5.png)

**Comment by vz3** [comment]
@jeremiak

**Comment by vz3** [comment]
@thisisdano @juliaelman @msecret for visibility

**Comment by juliasolorzano** [comment]
@vz3 nice work!

Once the design is 👍  it would be great to talk about how we implement the code base not only into `cg-style` but the pattern library itself. //cc @msecret

**Comment by thisisdano** [comment]
I've got plenty of ideas on how to work on this, which I'll work on today and post soon — but I gotta say, I wish we hadn't gotten (somewhat inadvertently) hardened into this new refactor style. We're gonna do all this work; build a whole pattern library based on it. It bums me out.

**Comment by msecret** [comment]
@thisisdano I'm a little unclear what you mean, do you mean the visual style changing or how cg-style's styleguide is changing to using Fractal?

**Comment by thisisdano** [comment]
Here are some initial thoughts on the some of the app settings sections. It mostly follows the same patterns as above with a bit more distinguishing color. 

Dropdown from each item's `edit` button could include `delete`.

Items expand to accommodate edit options when editable. 

Routes attempt a one-line route constructor. I also added a place to preview the constructed route for clarity. I also added route limit usage to the header of the routes section. The carat at the end of a route would be a link to the live URL.

In Limits and Quotas, I tried to rough out how a slider might work for Application Limits, editable once edit is selected. The slider would have limits set at the current usage and the available limit in the space or org, wherever it is set — I think it MUST be set in one of those places? Are there limitless orgs?? User could also set the value manually in the input box at the bottom of the expanded item. I wrote out the available space in a separate line rather than crowd the graph with further text. 

When the graph "expands" for editing, I have the app usage and space/org usage bars widening, but not the available bar, forming a kind of "rail" that the slider could slide on.

I also threw in a usage sparkline for fun.

![app-settings](https://cloud.githubusercontent.com/assets/11464021/17900751/445a0686-6915-11e6-957f-8161cda5ce5a.png)

**Comment by thisisdano** [comment]
A question about Limits and Quotas, though — does a limit or a quota "reserve" the space within the larger hierarchy? Or can limits and quotas "overlap"? For example:

A space has a quota of 1GB. It has five apps within it. Can each app have a limit of 1GB (overlapping), or must all the application limits _in total_ stay within the 1GB quota, like 5 limits of 200 MB each (reserved)? I can see how overlapping limits could be confusing for users — if they set a limit that allowed continuous deployment, but another app "encroached" and pushed the first app's usage over 50%.

This has big effects on how we display availability. I suspect that the system uses overlapping limits rather than reserved limits (and remaining availability would be calculated based on actual other app's usages rather than their limits/reservations), but perhaps there's an argument for moving toward reservations for planning and stability.

**Comment by vz3** [comment]
@thisisdano Can you share your sketch file for this

**Comment by thisisdano** [comment]
[uswds-cg-fork-dow.zip](https://github.com/18F/cg-design/files/433189/uswds-cg-fork-dow.zip)

**Comment by thisisdano** [comment]
Here are a few more application settings sketches based on feedback from @vz3 
- These now align to a 64px/16px grid. I made one 6c and one 7c.
- Modified the highlight color
- Worked on clarity of slider
- Developed error states
- Worked on clarity of graph, especially remaining space in space/org
- Adjusted color/typography
- Changed edit/delete button type for entries

Also playing around with the activity log, and with collecting all settings in a bordered "card", rather than a single setting per card (see the activity graphic for an example of this).

---

**Application settings @ 7c width**
![app-settings-v2-7c](https://cloud.githubusercontent.com/assets/11464021/17938947/0b6e5a02-69dd-11e6-9584-e8c05e533d3a.png)

---

**Application settings @ 6c width**
![app-settings-v-6c](https://cloud.githubusercontent.com/assets/11464021/17938952/177da51e-69dd-11e6-8bbd-b30d65376ef8.png)

---

**Activity and settings together**
![activity-log-insitu](https://cloud.githubusercontent.com/assets/11464021/17938967/2641d5fc-69dd-11e6-97b9-6f74bfa7e6a3.png)

---

[Sketch file](https://github.com/18F/cg-design/files/435179/uswds-cg-fork-dow-v2.zip)

**Comment by jeremiak** [comment]
These look really cool, and I think the route editing interface is pretty cool!

Is it right to assume that the slider for Disk limits and the "Application limit" text field are supposed to represent the same value? If so, that's cool and something that matches up with the capabilities of the platform ([relevant docs](https://docs.cloud.gov/apps/limits/)).

**Comment by thisisdano** [comment]
@jeremiak that's correct, about the text field and slider representing the same values

**Comment by thisisdano** [comment]
We were looking at these a bit in my crit group, and there was definitely some confusion about the distinction between a **limit** (Application limit) and a **quota** (Space quota). Beyond the idea that there should be a consistent way of describing the boundary around a specific kind of usage, they also thought that 'quota' didn't imply a _boundary_, rather it implied a _goal_ (as in "meeting a sales quota").

I'd never thought of the word quota like that, but I should have. And the more I think about it, it seems like a real flaw in the Cloud Foundry taxonomy — one that we might want to work to address, whether in our own implementation, or all the way at the CF source.

I wonder if anyone has any insight into the quota/limit question — why this exists in an otherwise pretty clear, elegant, and rational framework....

**Comment by vz3** [comment]
@thisisdano useful feedback! i'd like to do a microcopy review with @brittag, perhaps this coming sprint or maybe next

**Comment by thisisdano** [comment]
Here's a new iteration on the settings/usage panel: 
- taking a look at 'fusing' consecutive panels. so, in this version all the panels underneath `Application settings` fuse into one long panel.
- I'm showing the "uniqueness" error state in the route builder underneath the preview because this kind of error (as opposed to malformed input) may not be _exactly_ in the `host`, `path`, or `domain` inputs, rather in the combination of the three: the entire route.
- I made the `Apply` button inactive in the error state, since the user shouldn't be able to apply a change in error.

---

![app-settings-v3-6c](https://cloud.githubusercontent.com/assets/11464021/17978809/9e34dc1a-6aac-11e6-8983-074665214436.png)

[Download Sketch file](https://github.com/18F/cg-design/files/437627/uswds-cg-fork-dow-v3.zip)

**Comment by mogul** [comment]
@thisisdano:

> A question about Limits and Quotas, though — does a limit or a quota "reserve" the space within the larger hierarchy? Or can limits and quotas "overlap"?

It's definitely a reservation.

**Comment by thisisdano** [comment]
@mogul phew. very good. i'd imagined some real complications otherwise.

**Comment by suprenant** [comment]
Contingent upon some minor design tweaks, @vz3 accepts this. @msecret can you please validate that this matches requirements?

**Comment by vz3** [comment]
@thisisdano I'm going to request a small tweak here because I still think the slider bar still gets lost within its bounds. Can you pull out the blue and green to the side of the handles?

**Comment by suprenant** [comment]
Moving this back to the backlog as we discussed holding on scale for this sprint

@vz3 @thisisdano
